/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sv.udb.vistas;

import com.sv.udb.modelos.Conexion;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.util.HashMap;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.data.JRMapArrayDataSource;
import net.sf.jasperreports.engine.export.JRXlsExporter;
import net.sf.jasperreports.engine.export.JRXlsExporterParameter;
import net.sf.jasperreports.engine.export.ooxml.JRDocxExporter;

/**
 *
 * @author Raul
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEquipos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEqPDF = new javax.swing.JButton();
        btnEqWORD = new javax.swing.JButton();
        btnEqEXCEL = new javax.swing.JButton();
        pnlEquipos1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnJugPDF = new javax.swing.JButton();
        btnJugEXCEL = new javax.swing.JButton();
        btnJugWORD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlEquipos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Equipos");

        btnEqPDF.setText("PDF");
        btnEqPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqPDFActionPerformed(evt);
            }
        });

        btnEqWORD.setText("WORD");
        btnEqWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqWORDActionPerformed(evt);
            }
        });

        btnEqEXCEL.setText("EXCEL");
        btnEqEXCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqEXCELActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEquiposLayout = new javax.swing.GroupLayout(pnlEquipos);
        pnlEquipos.setLayout(pnlEquiposLayout);
        pnlEquiposLayout.setHorizontalGroup(
            pnlEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEquiposLayout.createSequentialGroup()
                .addGroup(pnlEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEquiposLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnEqPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(btnEqEXCEL))
                    .addGroup(pnlEquiposLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(pnlEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(btnEqWORD))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        pnlEquiposLayout.setVerticalGroup(
            pnlEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEquiposLayout.createSequentialGroup()
                .addGroup(pnlEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEquiposLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(pnlEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEqEXCEL)
                            .addComponent(btnEqPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlEquiposLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 47, Short.MAX_VALUE)))
                .addComponent(btnEqWORD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlEquipos1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Jugadores");

        btnJugPDF.setText("PDF");
        btnJugPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugPDFActionPerformed(evt);
            }
        });

        btnJugEXCEL.setText("EXCEL");
        btnJugEXCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugEXCELActionPerformed(evt);
            }
        });

        btnJugWORD.setText("WORD");
        btnJugWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugWORDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEquipos1Layout = new javax.swing.GroupLayout(pnlEquipos1);
        pnlEquipos1.setLayout(pnlEquipos1Layout);
        pnlEquipos1Layout.setHorizontalGroup(
            pnlEquipos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEquipos1Layout.createSequentialGroup()
                .addGroup(pnlEquipos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEquipos1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel2))
                    .addGroup(pnlEquipos1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnJugPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlEquipos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEquipos1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(btnJugWORD))
                            .addGroup(pnlEquipos1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(btnJugEXCEL)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        pnlEquipos1Layout.setVerticalGroup(
            pnlEquipos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEquipos1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(pnlEquipos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnJugEXCEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJugPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJugWORD)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEquipos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlEquipos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEqPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqPDFActionPerformed
        // TODO add your handling code here:
         try
        {
            Connection myconn;
            myconn=new Conexion().getConn();
            String jrxmlFileName = new File("src/main/java/com/sv/udb/reportes/Equipos.jrxml").getAbsolutePath();
            String jasperFileName = new File("src/main/java/com/sv/udb/reportes/Equipos.jasper").getAbsolutePath();
            String pdfFileName = new File("reportes/pdf/Equipos.pdf").getAbsolutePath();
              //Compilando jasperreport
            net.sf.jasperreports.engine.JasperCompileManager.compileReportToFile(jrxmlFileName, jasperFileName);
            JasperPrint print = (JasperPrint)JasperFillManager.fillReport(jasperFileName, null,myconn);
            
            //guardando
            JasperExportManager.exportReportToPdfFile(print, pdfFileName);
             //mostrar en el jasperviewer
             JasperViewer.viewReport(print, false);
            //mostrando
            if (Desktop.isDesktopSupported()) {
                try {
                    Desktop.getDesktop().open(new File(pdfFileName));
                } catch (IOException ex) {
                    System.out.println("No abrió :c " + ex);
                }
            }
            
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnEqPDFActionPerformed

    private void btnEqWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqWORDActionPerformed
        // TODO add your handling code here:
         try
        {
            Connection myconn;
            myconn=new Conexion().getConn();
            String jrxmlFileName = new File("src/main/java/com/sv/udb/reportes/Equipos.jrxml").getAbsolutePath();
            String jasperFileName = new File("src/main/java/com/sv/udb/reportes/Equipos.jasper").getAbsolutePath();
            String wordFileName = new File("reportes/word/Equipos.docx").getAbsolutePath();
              //Compilando jasperreport
            net.sf.jasperreports.engine.JasperCompileManager.compileReportToFile(jrxmlFileName, jasperFileName);
            JasperPrint print = (JasperPrint)JasperFillManager.fillReport(jasperFileName, null,myconn);
            
            JRDocxExporter exporter = new JRDocxExporter();
            exporter.setParameter(JRExporterParameter.JASPER_PRINT, print);
            exporter.setParameter(JRExporterParameter.OUTPUT_FILE_NAME, wordFileName);
            exporter.exportReport();
            //mostrando
            if (Desktop.isDesktopSupported()) {
                try {
                    Desktop.getDesktop().open(new File(wordFileName));
                } catch (IOException ex) {
                    System.out.println("No abrió :c " + ex);
                }
            }
            
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnEqWORDActionPerformed

    private void btnEqEXCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqEXCELActionPerformed
        // TODO add your handling code here:
         try
        {
            Connection myconn;
            myconn=new Conexion().getConn();
            String jrxmlFileName = new File("src/main/java/com/sv/udb/reportes/Equipos.jrxml").getAbsolutePath();
            String jasperFileName = new File("src/main/java/com/sv/udb/reportes/Equipos.jasper").getAbsolutePath();
            String wordFileName = new File("reportes/excel/Equipos.xls").getAbsolutePath();
              //Compilando jasperreport
            net.sf.jasperreports.engine.JasperCompileManager.compileReportToFile(jrxmlFileName, jasperFileName);
            JasperPrint print = (JasperPrint)JasperFillManager.fillReport(jasperFileName, null,myconn);
            
            JRDocxExporter exporter = new JRDocxExporter();
            exporter.setParameter(JRExporterParameter.JASPER_PRINT, print);
            exporter.setParameter(JRExporterParameter.OUTPUT_FILE_NAME, wordFileName);
            exporter.exportReport();
            //mostrando
            if (Desktop.isDesktopSupported()) {
                try {
                    Desktop.getDesktop().open(new File(wordFileName));
                } catch (IOException ex) {
                    System.out.println("No abrió :c " + ex);
                }
            }
            
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnEqEXCELActionPerformed

    private void btnJugPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugPDFActionPerformed
        // TODO add your handling code here:
          try
        {
            Connection myconn;
            myconn=new Conexion().getConn();
            String jrxmlFileName = new File("src/main/java/com/sv/udb/reportes/Jugadores.jrxml").getAbsolutePath();
            String jasperFileName = new File("src/main/java/com/sv/udb/reportes/Jugadores.jasper").getAbsolutePath();
            String pdfFileName = new File("reportes/pdf/Jugadores.pdf").getAbsolutePath();
              //Compilando jasperreport
            net.sf.jasperreports.engine.JasperCompileManager.compileReportToFile(jrxmlFileName, jasperFileName);
            JasperPrint print = (JasperPrint)JasperFillManager.fillReport(jasperFileName, null,myconn);
            
            //guardando
            JasperExportManager.exportReportToPdfFile(print, pdfFileName);
             //mostrar en el jasperviewer
             JasperViewer.viewReport(print, false);
            //mostrando
            if (Desktop.isDesktopSupported()) {
                try {
                    Desktop.getDesktop().open(new File(pdfFileName));
                } catch (IOException ex) {
                    System.out.println("No abrió :c " + ex);
                }
            }
            
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnJugPDFActionPerformed

    private void btnJugWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugWORDActionPerformed
        // TODO add your handling code here:
         try
        {
            Connection myconn;
            myconn=new Conexion().getConn();
            String jrxmlFileName = new File("src/main/java/com/sv/udb/reportes/Jugadores.jrxml").getAbsolutePath();
            String jasperFileName = new File("src/main/java/com/sv/udb/reportes/Jugadores.jasper").getAbsolutePath();
            String wordFileName = new File("reportes/word/Jugadores.docx").getAbsolutePath();
              //Compilando jasperreport
            net.sf.jasperreports.engine.JasperCompileManager.compileReportToFile(jrxmlFileName, jasperFileName);
            JasperPrint print = (JasperPrint)JasperFillManager.fillReport(jasperFileName, null,myconn);
            
            JRDocxExporter exporter = new JRDocxExporter();
            exporter.setParameter(JRExporterParameter.JASPER_PRINT, print);
            exporter.setParameter(JRExporterParameter.OUTPUT_FILE_NAME, wordFileName);
            exporter.exportReport();
            //mostrando
            if (Desktop.isDesktopSupported()) {
                try {
                    Desktop.getDesktop().open(new File(wordFileName));
                } catch (IOException ex) {
                    System.out.println("No abrió :c " + ex);
                }
            }
            
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnJugWORDActionPerformed

    private void btnJugEXCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugEXCELActionPerformed
        // TODO add your handling code here:
          try
        {
            Connection myconn;
            myconn=new Conexion().getConn();
            String jrxmlFileName = new File("src/main/java/com/sv/udb/reportes/Jugadores.jrxml").getAbsolutePath();
            String jasperFileName = new File("src/main/java/com/sv/udb/reportes/Jugadores.jasper").getAbsolutePath();
            String wordFileName = new File("reportes/excel/Jugadores.xls").getAbsolutePath();
              //Compilando jasperreport
            net.sf.jasperreports.engine.JasperCompileManager.compileReportToFile(jrxmlFileName, jasperFileName);
            JasperPrint print = (JasperPrint)JasperFillManager.fillReport(jasperFileName, null,myconn);
            
            JRDocxExporter exporter = new JRDocxExporter();
            exporter.setParameter(JRExporterParameter.JASPER_PRINT, print);
            exporter.setParameter(JRExporterParameter.OUTPUT_FILE_NAME, wordFileName);
            exporter.exportReport();
            //mostrando
            if (Desktop.isDesktopSupported()) {
                try {
                    Desktop.getDesktop().open(new File(wordFileName));
                } catch (IOException ex) {
                    System.out.println("No abrió :c " + ex);
                }
            }
            
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnJugEXCELActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEqEXCEL;
    private javax.swing.JButton btnEqPDF;
    private javax.swing.JButton btnEqWORD;
    private javax.swing.JButton btnJugEXCEL;
    private javax.swing.JButton btnJugPDF;
    private javax.swing.JButton btnJugWORD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnlEquipos;
    private javax.swing.JPanel pnlEquipos1;
    // End of variables declaration//GEN-END:variables
}
